# Test message dropped when no rules match

[logging]
log_ruler_droped_msg = true

[[rules]]
name = "R001"
enable = true
sender_name = "apprise"
match_from_value = "*@allowed.com"
new_to_value = "pover://user@token"

[[rules]]
name = "R002"
enable = true
sender_name = "smtp"
match_title = "ALERT*"
new_to_value = "archive@alerts.com"